apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    service: load
spec:
  replicas: 1
  selector:
    matchLabels:
      service: load
  template:
    metadata:
      labels:
        service: load
    spec:
      containers:
      - name: load
        env:
          - name: HOST
            value: "http://web:8080/"
          - name: NUM_CLIENTS
            value: "1"
          - name: SILENT
            value: "1"
          - name: ERROR
            value: "0"
        image: robotshop/rs-load:latest
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 400Mi
